version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=travel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
        ports:
            - '3307:3306'

    backend:
        build: ./backend
        working_dir: /application
        volumes:
            - './backend:/application'
        ports:
            - '8000:8000'
        command: >
            sh -c "
                php artisan serve --host=0.0.0.0 --port=8000
            "

    migrate:
        build: ./backend
        working_dir: /application
        volumes:
            - './backend:/application'
        depends_on:
            - mysql
        command: >
            sh -c "
                if [ ! -f .env ]; then cp .env.example .env; fi &&
                composer install &&
                php artisan key:generate &&
                php artisan migrate:fresh --seed
            "
    frontend:
        build: ./frontend
        working_dir: /application
        volumes:
            - './frontend:/application'
        ports:
            - '3000:5173'
        command: >
            sh -c "
                npm install &&
                npm run dev
            "
